export const ticketActionTypes = {
    SET_TICKETS: 'SET_TICKETS',
    SELECTED_TICKET: 'SELECTED_TICKET',
    REMOVE_SELECTED_TICKET: 'REMOVE_SELECTED_TICKET',
/*     TREAT_SELECTED_TICKET: 'TREAT_SELECTED_TICKET',
    CLOSE_SELECTED_TICKET: 'CLOSE_SELECTED_TICKET', */
    FILTERING_TICKETS: 'FILTERING_TICKETS',
    FILTER_TICKETS_BY_STATUS: 'FILTER_TICKETS_BY_STATUS',
    ADD_TICKET: 'ADD_TICKET',
    ASSIGN_TICKET: 'ASSIGN_TICKET',
    CLOSE_TICKET: 'CLOSE_TICKET',
    GET_USER_NOTIFICATIONS: 'GET_USER_NOTIFICATIONS',
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    READ_NOTIFICATION: 'READ_NOTIFICATION',
    GET_NOTIFICATION_TICKETS: 'GET_NOTIFICATION_TICKETS',
}