export const ticketActionTypes = {
    SET_TICKETS: 'SET_TICKETS',
    SELECTED_TICKET: 'SELECTED_TICKET',
    REMOVE_SELECTED_TICKET: 'REMOVE_SELECTED_TICKET',
    ADD_TICKET: 'ADD_TICKET',
    ASSIGN_TICKET: 'ASSIGN_TICKET',
    CLOSE_TICKET: 'CLOSE_TICKET'
}